### ISSUE TITLE
Getting response from request

### ISSUE THREAD

**Issue by q60** [ducdetronquito/http#22]
i may sound silly, because i am pretty new to the language, but can i get response from request in your library? i am using some API to GET something from it. thanks in advance.

**Comment by ducdetronquito** [comment]
Hi @q60,

Not a silly question at all: the *http* package only exists to provide some core types that can be used in order to deal with HTTP, like a `Url`, or a `Headers` type. But it does not do any real requests.

To make HTTP requests, I can suggest you to use an HTTP client like [requestz](https://github.com/ducdetronquito/requestz) :)
It is very early stage at this point, so do not hesitate to create issues if you encounter bugs, missing features or unintuitive APIs !

**Comment by q60** [comment]
thanks for the answer, but i really need, to make a HTTP<ins>S</ins> GET request to some API...

**Comment by ducdetronquito** [comment]
Yeah, you can make HTTPS requests too !

Example here: https://gist.github.com/ducdetronquito/c0d5b3230843c4ffd2284c90a5b527c8

**Comment by q60** [comment]
thanks!!!

**Comment by q60** [comment]
hmm, it yields a whole lot of errors....

**Comment by ducdetronquito** [comment]
Could you open an issue on requestz repository with the code to reproduce the bug and the errors you have ?
